spring:
  profiles:
    active: dev
  cloud:
    #dataid = ${prefix}-${spring.profiles.active}.${file-extension}
    #所以此处为 product-center-dev.properties
    nacos:
      discovery:
        server-addr: 192.168.5.103:8848
        namespace: e9b05a93-ae8e-47af-883f-b061d8c75861
        group: order1
        #cluster-name: WH
        #metadata:
          #version: v1
      config:
        server-addr: 192.168.5.103:8848
        #只支持yaml和properties
        file-extension: yaml
  application:
    name: product-center
server:
  port: 8083