server:
  port: 8080
spring:
  #给项目来个名字
  application:
    name: rabbitmq-provider
  #配置rabbitMq 服务器
  rabbitmq:
    host: 192.168.31.101
    port: 5672
    username: hujian
    password: hujian
    #虚拟host 可以不设置,使用server默认host
    virtual-host: /hujian
    listener:
      direct:
        acknowledge-mode: manual
        qu
