server:
  port: 8089
spring:
  datasource:
    name: bs_db
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: hujian
    password: xq19930906
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/
  redis:
    port: 6379
    host: 192.168.8.88
    timeout: 5000
    database: 0
    password: hujian
    maxIdle: 8
    minIdle: 8
    maxActive: 8
    maxWaitMillis: -1
  redisson:
    file:classpath:redisson.yaml
mybatis:
  mapper-locations: classpath:mappings/*Mapper.xml
  type-aliases-package: com.hujian.redis


